version: '3.8'
services:
    main:
        build:
            context: .
            dockerfile: Dockerfile
        command: 'php artisan serve --host=0.0.0.0'
        volumes:
            - .:/app
        ports:
            - 8888:8000
#        depends_on:
#            - mariadb

#    queue:
#        build:
#            context: .
#            dockerfile: Dockerfile
#        command: 'php artisan queue:work'
#        depends_on:
#            - mariadb

#    mariadb:
#        #platform: linux/x86_64
#        image: mariadb:10.2
#        #command: mysqld
#        #restart: always
#        environment:
#            MARIADB_DATABASE: rise
#            MYSQL_USER: admin
#            MYSQL_PASSWORD: admin
#            #MYSQL_ROOT: admin
#            #MYSQL_PASSWORD: admin
#            MYSQL_ROOT_PASSWORD: root
#        volumes:
#            - ./storage/dbdata:/var/lib/mysql
#        ports:
#            - 3306:3306
